### ISSUE TITLE
Missing file for gene search

### ISSUE THREAD

**Issue by WhirlFirst** [snap-stanford/BioDiscoveryAgent#1]
Hi,

I found that there is a missing file:
https://github.com/snap-stanford/BioDiscoveryAgent/blob/5c6851aa5173c8c07621c5659d3d0edf74b910e2/tools.py#L235

Could you also share this file on GitHub? Thanks!

**Comment by yhr91** [comment]
Sorry for the late reply here. The achilles gene features dataset can be downloaded from [here](https://ndownloader.figshare.com/files/25494359) 

We will also be updating the repository soon so that these files can be downloaded directly
